### PR TITLE
[4.0] haproxy: Check for existence of "content[:stick]"

### PR DESCRIPTION
**Pull request by stefannica**
(backports #258)

After a cowbar-ha update, the 'stick' attribute introduced in PR #209 is missing from the existing `node[:haproxy][sections]` entries, which may result in errors such as:

```
Chef::Mixin::Template::TemplateError
------------------------------------
undefined method `[]' for nil:NilClass
```

This PR adds checks for the existence of the 'stick' attribute before dereferencing it.

Fixes [bsc#1062889](https://bugzilla.suse.com/show_bug.cgi?id=1062889).

### CODE REVIEW

**Comment by stefannica** [comment]
[P2: Bug 1062889 - #L3 Error executing action `create` on haproxy.cfg after applying patches](https://trello.com/c/uG74VIzN/514-p2-bug-1062889-l3-error-executing-action-create-on-haproxycfg-after-applying-patches)
